In [5]:
import pandas as pd
pd.set_option('display.max_columns', None)

cleaned_df = pd.read_csv("2025-cleaned.csv")
messy_df = pd.read_csv("all-messy.csv")

In [6]:
cleaned_df.head()

,address,name,fcode_des,category_original,subcategory_original,lat,long
0,244 Augusta,The Dark Side Studio,NaN,ARTS & PERFORMANCE,ARTS ORGANIZATION SPACE,43.655518,-79.402608
1,392 Spadina Ave unit 2,Bad Dog Comedy Studio,NaN,ARTS & PERFORMANCE,ARTS ORGANIZATION SPACE,NaN,NaN
2,145 Augusta Ave,Polyester Studio,Mixed Use,ARTS & PERFORMANCE,FINE ARTS STUDIO,43.652552,-79.400950
3,250 Augusta Ave,SHVRK STUDIO,Unknown,ARTS & PERFORMANCE,FINE ARTS STUDIO,43.655592,-79.402773
4,183 Augusta Ave,Artographics Ltd.,NaN,ARTS & PERFORMANCE,GALLERY,43.653434,-79.401411

In [7]:
messy_df.head()

,primary_address,fcode_des,ownership_2025,owner_2025,establishment_2025_temporary,name_2025,category_2025,sub_category_2025,notes,name_2020,category_2020,sub_category_2020,name_2019,category_2019,sub_category_2019,name_2015,category_2015,sub_category_2015,name_2011,category_2011,sub_category_2011,name_2007,category_2007,sub_category_2007,name_1989,category_1989,sub_category_1989,residential_units,commercial_units,primary_zip,secondary_zip,primary_country_code,federal_district,geo_id,long,lat,ward_name
0,138 Augusta Ave,Mixed Use,NaN,NaN,Hair Salon,Grace Hair Salon,SERVICES,SALON,NaN,Grace Hair Salon,SERVICES,SALON,Grace Hair Salon,SERVICES,SALON,Grace Hair Salon,SERVICES,SALON,Grace Hair Salon,SERVICES,SALON,Grace Hair Salon,SERVICES,SALON,NaN,NaN,NaN,4,1,M5T,1H7,CA,University-Rosedale,10494678.0,-79.401470,43.652343,Trinity-Spadina (20)
1,141 Augusta Ave,Unknown,Individual,Pei Lay Chen and Tsan Fu Chen,NaN,NaN,NaN,NaN,NaN,Skye Ssutu,RETAIL,NEW CLOTHING,Indo-East Trading,RETAIL,NEW CLOTHING,Bike House,RETAIL,SPECIALTY STORE,Bike House,RETAIL,SPECIALTY STORE,Milk Mart,RETAIL,CONVENIENCE STORE,NaN,NaN,NaN,NaN,NaN,M5T,2L4,CA,University-Rosedale,10494661.0,-79.400969,43.652446,Trinity-Spadina (20)
2,143 Augusta Ave,Mixed Use,Corporate,Wigan Investments Limited,Clothing Store,Retro Heads Vintage,RETAIL,VINTAGE CLOTHING,NaN,Retro Heads,RETAIL,VINTAGE CLOTHING,Retro Heads,RETAIL,VINTAGE CLOTHING,VN Computer Systems,RETAIL,SPECIALTY STORE,VN Computer Systems,OFFICES,OFFICE SPACE,VN Computer Systems,OFFICES,OFFICE SPACE,NaN,NaN,NaN,2,1,M5T,2L4,CA,University-Rosedale,10494662.0,-79.400923,43.652505,Trinity-Spadina (20)
3,144 Augusta Ave,Commercial Location,Corporate,1194667 Ontario Inc,Tattoo Studio; Furniture Store,Tattoo Studio,SERVICES,TATTOO,NaN,Lu Cabinet Showroom,RETAIL,SPECIALTY STORE,Vacant,NaN,NaN,Logos Global Mission,SOCIAL/COMMUNITY,HOUSE OF WORSHIP,Olivia Chow Community Office,OFFICES,OFFICE SPACE,Olivia Chow Community Office,OFFICES,OFFICE SPACE,NaN,NaN,NaN,NaN,2,M5T,2L4,CA,University-Rosedale,10494676.0,-79.401575,43.652582,Trinity-Spadina (20)
4,145 Augusta Ave,Mixed Use,Corporate,"2635691 Ontario Inc, Edmund Chen, Thomas Hing ...",studio,Polyester Studio,ARTS & PERFORMANCE,FINE ARTS STUDIO,NaN,House of Energy,SERVICES,OTHER,House of Energy,SERVICES,OTHER,House of Energy,SERVICES,OTHER,House of Energy,NaN,NaN,Vacant,NaN,NaN,NaN,NaN,NaN,NaN,NaN,M5T,2L4,CA,University-Rosedale,10494663.0,-79.400950,43.652552,Trinity-Spadina (20)

In [9]:
messy_df = messy_df[['primary_address', 'name_2025', 'category_2025', 'sub_category_2025', 'long', 'lat']]
messy_df.head()

,primary_address,name_2025,category_2025,sub_category_2025,long,lat
0,138 Augusta Ave,Grace Hair Salon,SERVICES,SALON,-79.401470,43.652343
1,141 Augusta Ave,NaN,NaN,NaN,-79.400969,43.652446
2,143 Augusta Ave,Retro Heads Vintage,RETAIL,VINTAGE CLOTHING,-79.400923,43.652505
3,144 Augusta Ave,Tattoo Studio,SERVICES,TATTOO,-79.401575,43.652582
4,145 Augusta Ave,Polyester Studio,ARTS & PERFORMANCE,FINE ARTS STUDIO,-79.400950,43.652552

In [14]:
joined_df = cleaned_df.merge(messy_df, left_on='address', right_on='primary_address', how='outer')
joined_df.head(50)

,address,name,fcode_des,category_original,subcategory_original,lat_x,long_x,primary_address,name_2025,category_2025,sub_category_2025,long_y,lat_y
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 Fitzroy Ter,NaN,NaN,NaN,-79.400642,43.653252
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 Leonard Ave,NaN,NaN,NaN,-79.404003,43.653039
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 Leonard Pl,NaN,RESIDENTIAL,NaN,-79.403845,43.653334
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 Lippincott St,NaN,RESIDENTIAL,NaN,-79.405509,43.654827
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1 Wales Ave,NaN,RESIDENTIAL,NaN,-79.401657,43.653148
5,1-438 Spadina Ave,Toronto Hair Care Inc,NaN,SERVICES,SALON,43.656943,-79.399937,NaN,NaN,NaN,NaN,NaN,NaN
6,1-91 Oxford St,Enginess,NaN,SERVICES,OTHER,43.655963,-79.403323,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 Bellevue Ave,NaN,RESIDENTIAL,NaN,-79.403294,43.653385
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 Glen Baillie Pl,NaN,RESIDENTIAL,NaN,-79.399373,43.653852
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 Hickory St,NaN,RESIDENTIAL,NaN,-79.403251,43.652340
10,10 Kensington Ave,Urban Catwalk,Other Point of Interest,RETAIL,VINTAGE CLOTHING,43.653092,-79.400314,10 Kensington Ave,Urban Catwalk,RETAIL,VINTAGE CLOTHING,-79.400314,43.653092
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 Kensington Pl,NaN,NaN,NaN,-79.400952,43.653632
12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 Lippincott St,NaN,RESIDENTIAL,NaN,-79.406010,43.654796
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 Nassau St,NaN,NaN,NaN,-79.400186,43.655880
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10 Oxford St,NaN,NaN,NaN,-79.400392,43.656805
15,10 St Andrew St,Anshei Minsk Synagogue,Place of Worship,SOCIAL/COMMUNITY,HOUSE OF WORSHIP,43.654464,-79.399526,10 St Andrew St,Anshei Minsk Synagogue,SOCIAL/COMMUNITY,HOUSE OF WORSHIP,-79.399526,43.654464
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100 Bellevue Ave,NaN,RESIDENTIAL,NaN,-79.404529,43.656033
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100 Nassau St,NaN,NaN,NaN,-79.404444,43.655035
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,100 Oxford St,NaN,NaN,NaN,-79.405228,43.655851
19,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101 Oxford St,NaN,NaN,NaN,-79.404582,43.655526
20,102 Bellevue Ave,Kensington Suites,NaN,LODGING,HOTEL / HOSTEL,43.656095,-79.404234,102 Bellevue Ave,NaN,RESIDENTIAL,NaN,-79.404564,43.656078
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102 Nassau St,NaN,NaN,NaN,-79.404522,43.655086
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,102 Oxford St,NaN,NaN,NaN,-79.405273,43.655775
23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103 Bellevue Ave,NaN,NaN,NaN,-79.403983,43.656967
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,103 Oxford St,NaN,NaN,NaN,-79.404629,43.655517
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104 Bellevue Ave,NaN,RESIDENTIAL,NaN,-79.404553,43.656137
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104 Nassau St,NaN,NaN,NaN,-79.404580,43.655008
27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,104 Oxford St,NaN,NaN,NaN,-79.405332,43.655761
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,105 Oxford St,NaN,NaN,NaN,-79.404717,43.655503
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106 Bellevue Ave,NaN,RESIDENTIAL,NaN,-79.404558,43.656194
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106 Nassau St,NaN,NaN,NaN,-79.404657,43.655059
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,106 Oxford St,NaN,NaN,NaN,-79.405391,43.655732
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107 Oxford St,NaN,NaN,NaN,-79.404782,43.655498
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108 Bellevue Ave,NaN,RESIDENTIAL,NaN,-79.404600,43.656248
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108 Nassau St,NaN,NaN,NaN,-79.404716,43.654980
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,108 Oxford St,NaN,NaN,NaN,-79.405451,43.655720
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109 Oxford St,NaN,NaN,NaN,-79.404835,43.655489
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10A Kensington Ave,NaN,NaN,NaN,-79.400540,43.652985
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10R Bellevue Ave,NaN,RESIDENTIAL,NaN,-79.403455,43.653346
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11 Carlyle St,NaN,NaN,NaN,-79.404472,43.652193
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11 Casimir St,NaN,RESIDENTIAL,NaN,-79.403781,43.652350
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11 Glen Baillie Pl,NaN,RESIDENTIAL,NaN,-79.399206,43.653603
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11 Kensington Ave,NaN,RESIDENTIAL,NaN,-79.399765,43.652930
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11 Leonard Ave,NaN,RESIDENTIAL,NaN,-79.404237,43.653447
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11 Lippincott St,NaN,RESIDENTIAL,NaN,-79.405614,43.655081
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11 Lippincott St,NaN,NaN,NaN,-79.405501,43.655135
46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11 Oxford St,NaN,NaN,NaN,-79.400318,43.656401
47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11 Wales Ave,NaN,RESIDENTIAL,NaN,-79.402001,43.653075
48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110 Bellevue Ave,NaN,RESIDENTIAL,NaN,-79.404604,43.656304
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110 Nassau St,NaN,NaN,NaN,-79.404793,43.655031

In [15]:
len(joined_df)

1209

In [16]:
joined_df.to_csv("joined_df.csv", index=False)